import { useState, useEffect } from "react";
import { Loader2, Sparkles, Lightbulb, X, PenTool, Copy } from "lucide-react";
import { ErrorMessage } from "../components/ErrorMessage";
import { apiPost } from "../utils/api";
import { loadFromStorage, saveToStorage } from "../utils/storage";

export const IdeasPage = ({ savedVideos, setCurrentPage }) => {
  const [ideas, setIdeas] = useState(() => loadFromStorage("optimus_ideas", []));
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState(null);

  useEffect(() => { saveToStorage("optimus_ideas", ideas); }, [ideas]);

  const generateIdeas = async () => {
    if (savedVideos.length === 0) {
      setError("Save some videos to your vault first so we have something to riff on.");
      return;
    }
    setGenerating(true);
    setError(null);
    try {
      const persona = loadFromStorage("optimus_persona", {});
      const titles = savedVideos.slice(0, 10).map(v => `- "${v.title}" (${v.platform})`).join("\n");
      const prompt = `Based on these high-performing short-form videos:\n${titles}\n\n${persona.niche ? `Creator niche: ${persona.niche}. ` : ""}${persona.audience ? `Audience: ${persona.audience}. ` : ""}\n\nGenerate 6 original short-form video ideas the creator could make next. For each idea, provide: a title (under 60 chars), an angle (one sentence explaining the hook), and a format (e.g. explainer, story, list, react).\n\nReturn as a numbered list: "1. <title> — <angle> [<format>]".`;

      const r = await apiPost("/api/generate-script", { mode: "idea", input: prompt, duration: "short", tone: "Insightful" });
      const text = r.script || r.body || r.content || "";
      const lines = text.split("\n").filter(l => /^\s*\d+\./.test(l));
      const parsed = lines.map((l, i) => {
        const clean = l.replace(/^\s*\d+\.\s*/, "").trim();
        const formatMatch = clean.match(/\[([^\]]+)\]\s*$/);
        const format = formatMatch ? formatMatch[1] : "";
        const body = formatMatch ? clean.replace(/\s*\[[^\]]+\]\s*$/, "") : clean;
        const parts = body.split(/\s*[—–-]\s+/);
        return {
          id: Date.now() + i,
          title: (parts[0] || body).replace(/^["']|["']$/g, "").trim(),
          angle: (parts.slice(1).join(" — ") || "").trim(),
          format: format.trim(),
          createdAt: new Date().toISOString(),
        };
      }).filter(i => i.title);
      if (parsed.length === 0) throw new Error("Couldn't parse ideas — try again.");
      setIdeas(prev => [...parsed, ...prev].slice(0, 50));
    } catch (e) {
      setError(e.message);
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div>
      <div className="flex items-start justify-between mb-6 gap-4">
        <div>
          <h1 className="text-xl font-bold text-gray-900">Ideas</h1>
          <p className="text-sm text-gray-500 mt-1">Autogenerated ideas worth making, based on your saved videos and persona</p>
        </div>
        <button onClick={generateIdeas} disabled={generating}
          className="flex items-center gap-1.5 px-3 py-2 bg-gray-900 text-white rounded-lg text-sm font-medium hover:bg-gray-800 transition-colors disabled:opacity-50 flex-shrink-0">
          {generating ? <><Loader2 size={14} className="animate-spin" /> Generating…</> : <><Sparkles size={14} /> Generate ideas</>}
        </button>
      </div>

      {error && <div className="mb-4"><ErrorMessage message={error} onRetry={generateIdeas} /></div>}

      {ideas.length === 0 && !generating && (
        <div className="bg-white rounded-xl border border-gray-200 border-dashed p-12 text-center">
          <Lightbulb size={32} className="text-gray-300 mx-auto mb-3" />
          <p className="text-sm font-medium text-gray-700">No ideas yet</p>
          <p className="text-xs text-gray-500 mt-1 mb-4">
            {savedVideos.length === 0
              ? "Save some videos to your vault, then generate ideas riffing on what's working."
              : `You have ${savedVideos.length} saved videos. Click Generate ideas to get suggestions.`}
          </p>
          {savedVideos.length === 0 && (
            <button onClick={() => setCurrentPage("videos")}
              className="inline-flex items-center gap-1.5 px-3 py-2 bg-gray-900 text-white rounded-lg text-sm font-medium hover:bg-gray-800">
              Browse videos
            </button>
          )}
        </div>
      )}

      <div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">
        {ideas.map(idea => (
          <div key={idea.id} className="bg-white rounded-xl border border-gray-200 p-4 hover:border-gray-300 transition-all flex flex-col">
            <div className="flex items-start justify-between gap-2 mb-2">
              {idea.format && (
                <span className="text-[10px] font-semibold text-purple-700 bg-purple-50 px-2 py-0.5 rounded uppercase tracking-wider">
                  {idea.format}
                </span>
              )}
              <button onClick={() => setIdeas(prev => prev.filter(i => i.id !== idea.id))}
                className="p-1 -mr-1 text-gray-300 hover:text-red-500 transition-colors flex-shrink-0">
                <X size={14} />
              </button>
            </div>
            <h3 className="text-sm font-semibold text-gray-900 leading-snug mb-2">{idea.title}</h3>
            {idea.angle && <p className="text-xs text-gray-500 leading-relaxed flex-1">{idea.angle}</p>}
            <div className="flex gap-2 mt-3 pt-3 border-t border-gray-100">
              <button onClick={() => { saveToStorage("optimus_script_seed", idea); setCurrentPage("scripts"); }}
                className="flex-1 flex items-center justify-center gap-1 px-2.5 py-1.5 text-xs bg-gray-900 text-white rounded-lg hover:bg-gray-800 transition-colors font-medium">
                <PenTool size={12} /> Write script
              </button>
              <button onClick={() => navigator.clipboard.writeText(`${idea.title}${idea.angle ? "\n" + idea.angle : ""}`).catch(() => {})}
                className="px-2.5 py-1.5 text-xs text-gray-500 hover:text-gray-700 hover:bg-gray-50 rounded-lg transition-colors">
                <Copy size={12} />
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
