export const SAMPLE_WATCHLIST = [
  { id: "yt_1", name: "Macro Daddy", username: "_macro_daddy", platform: "Instagram Reels", subscribers: "773K", subscriberCount: 773000, thumbnail: "https://ui-avatars.com/api/?name=MD&background=FF6B6B&color=fff" },
  { id: "yt_2", name: "Alexa Stanco", username: "alexastancofit", platform: "Instagram Reels", subscribers: "409K", subscriberCount: 409000, thumbnail: "https://ui-avatars.com/api/?name=AC&background=4ECDC4&color=fff" },
  { id: "yt_3", name: "Coach Dango", username: "coachdango", platform: "Instagram Reels", subscribers: "1.4M", subscriberCount: 1400000, thumbnail: "https://ui-avatars.com/api/?name=CD&background=95E1D3&color=fff" },
  { id: "yt_4", name: "Dan Martell", username: "danmartell", platform: "YouTube Shorts", subscribers: "2.2M", subscriberCount: 2200000, thumbnail: "https://ui-avatars.com/api/?name=DM&background=F38181&color=fff" },
  { id: "yt_5", name: "Falke Fit", username: "falkefit", platform: "TikTok", subscribers: "339K", subscriberCount: 339000, thumbnail: "https://ui-avatars.com/api/?name=FF&background=AA96DA&color=fff" },
];

export const SAMPLE_VIDEOS = [
  { id: "sv_1", title: "Low calorie protein swaps you need to try", channel: { name: "Macro Daddy", thumbnail: "https://ui-avatars.com/api/?name=MD&background=FF6B6B&color=fff" }, platform: "YouTube Shorts", thumbnail: "https://picsum.photos/seed/v1/270/480", outlierScore: 1.3, views: 18000, viewsFormatted: "18K", likes: 720, likesFormatted: "720", timeAgo: "1d ago", url: "#" },
  { id: "sv_2", title: "Have you ever heard of this fitness hack?", channel: { name: "Alexa Stanco", thumbnail: "https://ui-avatars.com/api/?name=AC&background=4ECDC4&color=fff" }, platform: "YouTube Shorts", thumbnail: "https://picsum.photos/seed/v2/270/480", outlierScore: 1.0, views: 13000, viewsFormatted: "13K", likes: 520, likesFormatted: "520", timeAgo: "1d ago", url: "#" },
  { id: "sv_3", title: "Transform your body with this trick", channel: { name: "Coach Dango", thumbnail: "https://ui-avatars.com/api/?name=CD&background=95E1D3&color=fff" }, platform: "YouTube Shorts", thumbnail: "https://picsum.photos/seed/v3/270/480", outlierScore: 1.5, views: 25000, viewsFormatted: "25K", likes: 1500, likesFormatted: "1.5K", timeAgo: "2d ago", url: "#" },
  { id: "sv_4", title: "Fitness myths debunked in 60 seconds", channel: { name: "Dan Martell", thumbnail: "https://ui-avatars.com/api/?name=DM&background=F38181&color=fff" }, platform: "YouTube Shorts", thumbnail: "https://picsum.photos/seed/v4/270/480", outlierScore: 2.1, views: 42000, viewsFormatted: "42K", likes: 3360, likesFormatted: "3.4K", timeAgo: "3d ago", url: "#" },
  { id: "sv_5", title: "This changed my workout routine forever", channel: { name: "Falke Fit", thumbnail: "https://ui-avatars.com/api/?name=FF&background=AA96DA&color=fff" }, platform: "TikTok", thumbnail: "https://picsum.photos/seed/v5/270/480", outlierScore: 1.2, views: 19000, viewsFormatted: "19K", likes: 950, likesFormatted: "950", timeAgo: "1d ago", url: "#" },
  { id: "sv_6", title: "The #1 mistake people make at the gym", channel: { name: "Macro Daddy", thumbnail: "https://ui-avatars.com/api/?name=MD&background=FF6B6B&color=fff" }, platform: "YouTube Shorts", thumbnail: "https://picsum.photos/seed/v6/270/480", outlierScore: 1.8, views: 35000, viewsFormatted: "35K", likes: 2450, likesFormatted: "2.5K", timeAgo: "2d ago", url: "#" },
  { id: "sv_7", title: "Quick abs workout for busy people", channel: { name: "Alexa Stanco", thumbnail: "https://ui-avatars.com/api/?name=AC&background=4ECDC4&color=fff" }, platform: "YouTube Shorts", thumbnail: "https://picsum.photos/seed/v7/270/480", outlierScore: 1.4, views: 22000, viewsFormatted: "22K", likes: 1320, likesFormatted: "1.3K", timeAgo: "1d ago", url: "#" },
  { id: "sv_8", title: "Nutrition secrets from pro athletes", channel: { name: "Dan Martell", thumbnail: "https://ui-avatars.com/api/?name=DM&background=F38181&color=fff" }, platform: "YouTube Shorts", thumbnail: "https://picsum.photos/seed/v8/270/480", outlierScore: 1.6, views: 28000, viewsFormatted: "28K", likes: 1960, likesFormatted: "2K", timeAgo: "2d ago", url: "#" },
  { id: "sv_9", title: "5 minute morning energy boost", channel: { name: "Coach Dango", thumbnail: "https://ui-avatars.com/api/?name=CD&background=95E1D3&color=fff" }, platform: "YouTube Shorts", thumbnail: "https://picsum.photos/seed/v9/270/480", outlierScore: 0.9, views: 11000, viewsFormatted: "11K", likes: 330, likesFormatted: "330", timeAgo: "3d ago", url: "#" },
  { id: "sv_10", title: "How I get shredded without starving", channel: { name: "Falke Fit", thumbnail: "https://ui-avatars.com/api/?name=FF&background=AA96DA&color=fff" }, platform: "TikTok", thumbnail: "https://picsum.photos/seed/v10/270/480", outlierScore: 2.0, views: 38000, viewsFormatted: "38K", likes: 3040, likesFormatted: "3K", timeAgo: "1d ago", url: "#" },
  { id: "sv_11", title: "Mobility routine that actually works", channel: { name: "Macro Daddy", thumbnail: "https://ui-avatars.com/api/?name=MD&background=FF6B6B&color=fff" }, platform: "YouTube Shorts", thumbnail: "https://picsum.photos/seed/v11/270/480", outlierScore: 1.1, views: 16000, viewsFormatted: "16K", likes: 640, likesFormatted: "640", timeAgo: "2d ago", url: "#" },
  { id: "sv_12", title: "Meal prep for the entire week", channel: { name: "Dan Martell", thumbnail: "https://ui-avatars.com/api/?name=DM&background=F38181&color=fff" }, platform: "YouTube Shorts", thumbnail: "https://picsum.photos/seed/v12/270/480", outlierScore: 1.7, views: 32000, viewsFormatted: "32K", likes: 1920, likesFormatted: "1.9K", timeAgo: "3d ago", url: "#" },
];
